### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [mmaleki92/python_teaching#1]
Hi @mmaleki92 ,

great training resource here and great that you are sharing it open source! I was just wondering under which conditions one could reuse the code and materials provided here. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by mmaleki92** [comment]
Hi Robert @haesleinhuepf,

Thank you for your kind words! I'm glad you found the training resource helpful.

I appreciate your suggestion about adding a license file. I'm committed to making these materials freely available for use, modification, and distribution. Based on your recommendation and after some research, I have decided to apply the MIT License to this project. This will allow others to use the code and materials with minimal restrictions.

I've added a LICENSE file to the repository with the MIT License terms. You can now reuse the code and materials provided here under the conditions outlined in the license.

If you have any other suggestions I'll be glad to know,
Thanks again for your suggestion!

Best,
Morteza

**Comment by haesleinhuepf** [comment]
Fantastic thanks so much @mmaleki92 !
